export { default as Faq } from './Faq';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as MatchLineup } from './MatchLineup';
export { default as MatchLocation } from './MatchLocation';
export { default as MatchWeather } from './MatchWeather';
export { default as PageNotFound } from './PageNotFound';
export { default as Profile } from './Profile';
export { default as Register } from './Register';
