# This workflow performs a clean installation of node dependencies, cache/restore them,
# runs tests, lints and then formats the code.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
  JWT_PUBLIC_KEY: ${{secrets.JWT_PUBLIC_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn test
    - run: yarn lint
    - run: yarn format:write
